# Generated by Django 3.2.6 on 2021-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=35)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=35, null=True)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
    ]
