# Generated by Django 3.2.6 on 2021-10-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('local', models.CharField(blank=True, max_length=50)),
                ('modalidade', models.CharField(blank=True, max_length=50)),
                ('data', models.CharField(blank=True, max_length=50)),
                ('vice_capitao', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=25)),
                ('dia', models.CharField(max_length=25)),
                ('local', models.CharField(max_length=50)),
                ('aceite', models.CharField(default='Aguardando', max_length=25)),
                ('id_mando', models.IntegerField()),
                ('times', models.ManyToManyField(related_name='partidas', to='equipe.Time')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.CharField(max_length=25)),
                ('jogos', models.PositiveIntegerField(default=0)),
                ('gols', models.PositiveIntegerField(default=0)),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipe.time')),
            ],
        ),
        migrations.CreateModel(
            name='Capitao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=40)),
                ('psw', models.CharField(default='123456', max_length=40)),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipe.time')),
            ],
        ),
    ]
