# Generated by Django 3.2.6 on 2021-11-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumula',
            name='aceiteDesafiado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sumula',
            name='aceiteMandante',
            field=models.BooleanField(default=False),
        ),
    ]
