# Generated by Django 3.2.6 on 2021-09-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='jogadores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipe.jogador'),
        ),
    ]
