# Generated by Django 3.2.6 on 2021-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitao',
            name='cep',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitao',
            name='cpf',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='capitao',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='capitao',
            name='telefone',
            field=models.CharField(max_length=25),
        ),
    ]
