# Generated by Django 3.2.6 on 2021-10-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitao',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
