# Generated by Django 3.2.6 on 2021-09-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_auto_20210907_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitao',
            name='complemento',
            field=models.CharField(blank=True, default=0, max_length=35),
            preserve_default=False,
        ),
    ]
