# Generated by Django 3.2.6 on 2021-11-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_auto_20211104_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='resultado',
            field=models.CharField(default='', max_length=25),
        ),
    ]
