# Generated by Django 3.2.6 on 2021-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_partida_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='golPara',
            field=models.CharField(default='', max_length=25),
        ),
    ]
