# Generated by Django 3.2.6 on 2021-09-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_auto_20210920_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipe.time'),
        ),
    ]
