# Generated by Django 3.2.6 on 2021-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_alter_jogador_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='gols',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='jogos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
