# Generated by Django 3.2.6 on 2021-10-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0005_auto_20210926_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='vice_capitao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
