# Generated by Django 3.2.6 on 2021-10-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_time_vice_capitao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='data',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
