# Generated by Django 3.2.6 on 2021-10-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0007_alter_time_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=25)),
                ('mando', models.CharField(max_length=25)),
                ('dia', models.CharField(max_length=25)),
                ('local', models.CharField(max_length=50)),
                ('aceite', models.BooleanField()),
                ('times', models.ManyToManyField(related_name='partidas', to='equipe.Time')),
            ],
        ),
    ]
