# Generated by Django 3.2.6 on 2021-10-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0008_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='id_mando',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
