# Generated by Django 3.2.6 on 2021-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0010_remove_partida_mando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='aceite',
            field=models.CharField(default='Aguardando', max_length=25),
        ),
    ]
