# Generated by Django 3.2.6 on 2021-10-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0011_alter_partida_aceite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitao',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='capitao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='capitao',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='capitao',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='capitao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='capitao',
            name='numero',
        ),
        migrations.AddField(
            model_name='capitao',
            name='psw',
            field=models.CharField(default='123456', max_length=40),
        ),
    ]
