# Generated by Django 3.2.6 on 2021-10-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0012_auto_20211019_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitao',
            name='email',
            field=models.CharField(default='email@teste.com', max_length=50),
        ),
    ]
